# Generated by Django 5.1 on 2024-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='status_change_date',
            field=models.DateTimeField(),
        ),
    ]
