# Generated by Django 5.1 on 2024-10-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_image_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
    ]
